language: python

python: 3.8

branches: main

install:
  - pip install mkdocs

script: true

before_deploy:
  - mkdocs build --verbose --clean

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: site
  on:
    branch: main
  repo: prodigy413/prodigy413.github.io
  target_branch: main
