language: python

python: 3.8

#branches: main

install:
  - pip3 install mkdocs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
